# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python_Code\pyApkToolkit\NewKeyStoreDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_Dialog_NewKeyStore(object):
    def setupUi(self, Dialog_NewKeyStore):
        Dialog_NewKeyStore.setObjectName("Dialog_NewKeyStore")
        Dialog_NewKeyStore.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_NewKeyStore.resize(470, 426)
        Dialog_NewKeyStore.setMinimumSize(QtCore.QSize(470, 426))
        Dialog_NewKeyStore.setMaximumSize(QtCore.QSize(470, 426))
        self.line = QtWidgets.QFrame(Dialog_NewKeyStore)
        self.line.setGeometry(QtCore.QRect(45, 76, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label.setGeometry(QtCore.QRect(21, 76, 18, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 90, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_3.setGeometry(QtCore.QRect(21, 48, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_4.setGeometry(QtCore.QRect(263, 45, 48, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_5.setGeometry(QtCore.QRect(24, 156, 54, 12))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_8.setGeometry(QtCore.QRect(21, 164, 96, 12))
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(Dialog_NewKeyStore)
        self.groupBox.setGeometry(QtCore.QRect(8, 186, 449, 189))
        self.groupBox.setMinimumSize(QtCore.QSize(449, 189))
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(21, 20, 120, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(21, 47, 120, 12))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(21, 74, 78, 12))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(21, 100, 102, 12))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(21, 127, 108, 12))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(21, 154, 108, 12))
        self.label_16.setObjectName("label_16")
        self.lineEdit_Name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Name.setGeometry(QtCore.QRect(158, 20, 281, 20))
        self.lineEdit_Name.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_Name.setMaximumSize(QtCore.QSize(281, 20))
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.lineEdit_OrganizationalUnit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_OrganizationalUnit.setGeometry(QtCore.QRect(158, 50, 281, 20))
        self.lineEdit_OrganizationalUnit.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_OrganizationalUnit.setObjectName("lineEdit_OrganizationalUnit")
        self.lineEdit_Organization = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Organization.setGeometry(QtCore.QRect(158, 76, 281, 20))
        self.lineEdit_Organization.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_Organization.setObjectName("lineEdit_Organization")
        self.lineEdit_Locality = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Locality.setGeometry(QtCore.QRect(158, 102, 281, 20))
        self.lineEdit_Locality.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_Locality.setObjectName("lineEdit_Locality")
        self.lineEdit_State = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_State.setGeometry(QtCore.QRect(158, 128, 281, 20))
        self.lineEdit_State.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_State.setObjectName("lineEdit_State")
        self.lineEdit_CountryCode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CountryCode.setGeometry(QtCore.QRect(158, 154, 281, 20))
        self.lineEdit_CountryCode.setMinimumSize(QtCore.QSize(281, 20))
        self.lineEdit_CountryCode.setObjectName("lineEdit_CountryCode")
        self.lineEdit_KeyStorePath = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_KeyStorePath.setGeometry(QtCore.QRect(123, 16, 297, 20))
        self.lineEdit_KeyStorePath.setMinimumSize(QtCore.QSize(297, 20))
        self.lineEdit_KeyStorePath.setObjectName("lineEdit_KeyStorePath")
        self.lineEdit_StorePass = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_StorePass.setGeometry(QtCore.QRect(123, 45, 133, 20))
        self.lineEdit_StorePass.setMinimumSize(QtCore.QSize(133, 20))
        self.lineEdit_StorePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_StorePass.setObjectName("lineEdit_StorePass")
        self.lineEdit_StorePassConfirm = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_StorePassConfirm.setGeometry(QtCore.QRect(315, 45, 133, 20))
        self.lineEdit_StorePassConfirm.setMinimumSize(QtCore.QSize(133, 20))
        self.lineEdit_StorePassConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_StorePassConfirm.setObjectName("lineEdit_StorePassConfirm")
        self.pushButton_OpenKeystore = QtWidgets.QPushButton(Dialog_NewKeyStore)
        self.pushButton_OpenKeystore.setGeometry(QtCore.QRect(423, 16, 25, 20))
        self.pushButton_OpenKeystore.setMinimumSize(QtCore.QSize(25, 20))
        self.pushButton_OpenKeystore.setMaximumSize(QtCore.QSize(25, 20))
        self.pushButton_OpenKeystore.setObjectName("pushButton_OpenKeystore")
        self.label_6 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_6.setGeometry(QtCore.QRect(20, 104, 36, 12))
        self.label_6.setObjectName("label_6")
        self.lineEdit_Alias = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_Alias.setGeometry(QtCore.QRect(123, 100, 325, 20))
        self.lineEdit_Alias.setMinimumSize(QtCore.QSize(325, 20))
        self.lineEdit_Alias.setObjectName("lineEdit_Alias")
        self.lineEdit_KeyPassConfirm = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_KeyPassConfirm.setGeometry(QtCore.QRect(315, 128, 133, 20))
        self.lineEdit_KeyPassConfirm.setMinimumSize(QtCore.QSize(133, 20))
        self.lineEdit_KeyPassConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_KeyPassConfirm.setObjectName("lineEdit_KeyPassConfirm")
        self.lineEdit_KeyPass = QtWidgets.QLineEdit(Dialog_NewKeyStore)
        self.lineEdit_KeyPass.setGeometry(QtCore.QRect(123, 128, 133, 20))
        self.lineEdit_KeyPass.setMinimumSize(QtCore.QSize(133, 20))
        self.lineEdit_KeyPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_KeyPass.setObjectName("lineEdit_KeyPass")
        self.label_7 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_7.setGeometry(QtCore.QRect(20, 132, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(Dialog_NewKeyStore)
        self.label_17.setGeometry(QtCore.QRect(263, 128, 48, 12))
        self.label_17.setObjectName("label_17")
        self.spinBox_Validity = QtWidgets.QSpinBox(Dialog_NewKeyStore)
        self.spinBox_Validity.setGeometry(QtCore.QRect(123, 160, 40, 20))
        self.spinBox_Validity.setMinimum(1)
        self.spinBox_Validity.setProperty("value", 25)
        self.spinBox_Validity.setObjectName("spinBox_Validity")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_NewKeyStore)
        self.buttonBox.setGeometry(QtCore.QRect(300, 388, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog_NewKeyStore)
        QtCore.QMetaObject.connectSlotsByName(Dialog_NewKeyStore)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_KeyStorePath, self.pushButton_OpenKeystore)
        Dialog_NewKeyStore.setTabOrder(self.pushButton_OpenKeystore, self.lineEdit_StorePass)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_StorePass, self.lineEdit_StorePassConfirm)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_StorePassConfirm, self.lineEdit_Alias)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_Alias, self.lineEdit_KeyPass)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_KeyPass, self.lineEdit_KeyPassConfirm)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_KeyPassConfirm, self.spinBox_Validity)
        Dialog_NewKeyStore.setTabOrder(self.spinBox_Validity, self.lineEdit_Name)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_Name, self.lineEdit_OrganizationalUnit)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_OrganizationalUnit, self.lineEdit_Organization)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_Organization, self.lineEdit_Locality)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_Locality, self.lineEdit_State)
        Dialog_NewKeyStore.setTabOrder(self.lineEdit_State, self.lineEdit_CountryCode)

    def retranslateUi(self, Dialog_NewKeyStore):
        _translate = QtCore.QCoreApplication.translate
        Dialog_NewKeyStore.setWindowTitle(_translate("Dialog_NewKeyStore", "New Key Store"))
        self.label.setText(_translate("Dialog_NewKeyStore", "Key"))
        self.label_2.setText(_translate("Dialog_NewKeyStore", "Key store path:"))
        self.label_3.setText(_translate("Dialog_NewKeyStore", "Password:"))
        self.label_4.setText(_translate("Dialog_NewKeyStore", "Confirm:"))
        self.label_8.setText(_translate("Dialog_NewKeyStore", "Validity(years):"))
        self.groupBox.setTitle(_translate("Dialog_NewKeyStore", "Certificate"))
        self.label_9.setText(_translate("Dialog_NewKeyStore", "First and Last Name:"))
        self.label_10.setText(_translate("Dialog_NewKeyStore", "Organizational Unit:"))
        self.label_13.setText(_translate("Dialog_NewKeyStore", "Organization:"))
        self.label_14.setText(_translate("Dialog_NewKeyStore", "City or Locality:"))
        self.label_15.setText(_translate("Dialog_NewKeyStore", "State or Province:"))
        self.label_16.setText(_translate("Dialog_NewKeyStore", "Country Code (XX):"))
        self.lineEdit_Name.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">名称(CN)</span></p></body></html>"))
        self.lineEdit_Name.setText(_translate("Dialog_NewKeyStore", "arno"))
        self.lineEdit_OrganizationalUnit.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">组织单位(OU)</span></p></body></html>"))
        self.lineEdit_Organization.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">组织(O)</span></p></body></html>"))
        self.lineEdit_Locality.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">省市(L)</span></p></body></html>"))
        self.lineEdit_State.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">市或者洲(ST)</span></p></body></html>"))
        self.lineEdit_CountryCode.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">国家代码(C)</span></p></body></html>"))
        self.lineEdit_CountryCode.setText(_translate("Dialog_NewKeyStore", "86"))
        self.lineEdit_KeyStorePath.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">keystore.jks存储位置!</span></p></body></html>"))
        self.lineEdit_KeyStorePath.setText(_translate("Dialog_NewKeyStore", "keystore.jks"))
        self.lineEdit_StorePass.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">默认:arno123</span></p></body></html>"))
        self.lineEdit_StorePass.setText(_translate("Dialog_NewKeyStore", "arno123"))
        self.lineEdit_StorePassConfirm.setText(_translate("Dialog_NewKeyStore", "arno123"))
        self.pushButton_OpenKeystore.setText(_translate("Dialog_NewKeyStore", "..."))
        self.label_6.setText(_translate("Dialog_NewKeyStore", "Alias:"))
        self.lineEdit_Alias.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">别名</span></p></body></html>"))
        self.lineEdit_Alias.setText(_translate("Dialog_NewKeyStore", "arno"))
        self.lineEdit_KeyPassConfirm.setText(_translate("Dialog_NewKeyStore", "arno123"))
        self.lineEdit_KeyPass.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">默认:arno123</span></p></body></html>"))
        self.lineEdit_KeyPass.setText(_translate("Dialog_NewKeyStore", "arno123"))
        self.label_7.setText(_translate("Dialog_NewKeyStore", "Password:"))
        self.label_17.setText(_translate("Dialog_NewKeyStore", "Confirm:"))
        self.spinBox_Validity.setToolTip(_translate("Dialog_NewKeyStore", "<html><head/><body><p><span style=\" font-weight:600;\">有效期</span></p></body></html>"))

